name: Release Extension ZIP

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prepare extension folder
        run: |
          mkdir extension
          cp manifest.json extension/
          cp -r src/* extension/

      - name: Zip extension
        run: |
          cd extension
          zip -r ../chrome-extension.zip .

      - name: Create GitHub Release and upload ZIP
        uses: softprops/action-gh-release@v1
        with:
          files: chrome-extension.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

